language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install portalocker
    - pip install scipy
    - pip install cs207rbtree
script:
    - py.test
after_success:
    - coveralls
