language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install portalocker
    - pip install scipy
    - pip install -e .
    #- pip install cs207rbtree
    #- pip install timeseries
    #- pip install TimeseriesDB
    #- pip install Similarity
script:
    - py.test tests
after_success:
    - coveralls
